---
- name: Install and configure Elasticsearch
  hosts: elastic
  remote_user: sysop
  become: yes
  become_method: sudo
  collections:
    - community.docker  # Подключение коллекции community.docker
  roles:
    - elastic