all:
  hosts:
    bastion:
      ansible_host: 51.250.95.187
      ansible_user: sysop
      ansible_ssh_private_key_file: /home/vodin/.ssh/id_ed25519
    web1:
      ansible_host: 192.168.10.10
      ansible_user: sysop
      ansible_ssh_private_key_file: /home/vodin/.ssh/id_ed25519
      ansible_ssh_common_args: -o ProxyJump=sysop@51.250.95.187
    web2:
      ansible_host: 192.168.20.10
      ansible_user: sysop
      ansible_ssh_private_key_file: /home/vodin/.ssh/id_ed25519
      ansible_ssh_common_args: -o ProxyJump=sysop@51.250.95.187
    elastic: 
      ansible_host: 192.168.10.111
      ansible_user: sysop
      ansible_ssh_common_args: -o ProxyJump=sysop@51.250.95.187
    kibana: 
      ansible_host: 192.168.10.112
      ansible_user: sysop
      ansible_ssh_private_key_file: /home/vodin/.ssh/id_ed25519  
      ansible_ssh_common_args: -o ProxyJump=sysop@51.250.95.187
    zabbix:
      ansible_host: 192.168.10.110
      ansible_user: sysop
      ansible_ssh_private_key_file: /home/vodin/.ssh/id_ed25519
      ansible_ssh_common_args: -o ProxyJump=sysop@51.250.95.187
      
  children:
    bastions:
      hosts:
        bastion:
    webservers:
      hosts:
        web1:
        web2:
    monitoring:
      hosts:
        zabbix:
        kibana:
